// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoWinFormsApp.Data;

#nullable disable

namespace TodoWinFormsApp.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20260928045830_migrationfile")]
    partial class migrationfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoWinFormsApp.Models.TodoAssignee", b =>
                {
                    b.Property<string>("AssigneeId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasComment("担当者ID");

                    b.Property<string>("AssigneeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("担当者名");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("作成日時");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("表示順");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasComment("メールアドレス");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("利用状態");

                    b.Property<int>("LogType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("履歴処理区分");

                    b.Property<string>("LoggedFunctionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasComment("更新機能ID");

                    b.Property<string>("LoggedUserCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasComment("更新担当者");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("備考");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime")
                        .HasComment("更新日時");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasComment("ユーザーコード");

                    b.HasKey("AssigneeId")
                        .HasName("TodoAssignee_PKC");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("IdxTodoAssignee01");

                    b.HasIndex("IsActive", "DisplayOrder", "AssigneeName")
                        .IsDescending(true, false, false)
                        .HasDatabaseName("IdxTodoAssignee02");

                    b.ToTable("TodoAssignee", "dbo", t =>
                        {
                            t.HasComment("TODO担当者情報");

                            t.HasCheckConstraint("CK_TodoAssignee_DisplayOrder", "[DisplayOrder] BETWEEN 1 AND 9999");

                            t.HasCheckConstraint("CK_TodoAssignee_LogType", "[LogType] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("TodoWinFormsApp.Models.TodoTask", b =>
                {
                    b.Property<string>("TodoId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasComment("TODO ID");

                    b.Property<string>("AssigneeId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasComment("担当者ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasComment("作成日時");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("詳細");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasComment("期限");

                    b.Property<int>("LogType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("履歴処理区分");

                    b.Property<string>("LoggedFunctionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasComment("更新機能ID");

                    b.Property<string>("LoggedUserCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)")
                        .HasComment("更新担当者");

                    b.Property<int?>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("優先度");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("状態");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("TODOタイトル");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime")
                        .HasComment("更新日時");

                    b.HasKey("TodoId")
                        .HasName("TodoTask_PKC");

                    b.HasIndex("AssigneeId", "Status", "UpdatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IdxTodoTask02");

                    b.HasIndex("Status", "Priority", "DueDate", "UpdatedAt")
                        .IsDescending(false, true, false, true)
                        .HasDatabaseName("IdxTodoTask01");

                    b.ToTable("TodoTask", "dbo", t =>
                        {
                            t.HasComment("TODO情報");

                            t.HasCheckConstraint("CK_TodoTask_LogType", "[LogType] BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_TodoTask_Priority", "[Priority] BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_TodoTask_Status", "[Status] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("TodoWinFormsApp.Models.TodoTask", b =>
                {
                    b.HasOne("TodoWinFormsApp.Models.TodoAssignee", "Assignee")
                        .WithMany("TodoTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_TodoTask_TodoAssignee");

                    b.Navigation("Assignee");
                });

            modelBuilder.Entity("TodoWinFormsApp.Models.TodoAssignee", b =>
                {
                    b.Navigation("TodoTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
